---
- name: Remove logrotate.d configuration based on files
  become: true
  ansible.builtin.file:
    path: "{{ logrotate_logrotated_path }}/{{ item | basename }}"
    state: absent
  with_fileglob:
    - "{{ logrotate_local_logrotated_path }}/*[!.j2]"

- name: Remove logrotate.d configuration based on templates
  become: true
  ansible.builtin.file:
    path: "{{ logrotate_logrotated_path }}/{{ item | basename | splitext | first }}"
    state: absent
  with_fileglob:
    - "{{ logrotate_local_logrotated_path }}/*.j2"
