---
- name: Copy logrotate.d files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ logrotate_logrotated_path }}"
    owner: "{{ logrotate_file_owner }}"
    group: "{{ logrotate_file_group }}"
    mode: "{{ logrotate_file_mode }}"
    force: true
  with_fileglob:
    - "{{ logrotate_local_logrotated_path }}/*"
  register: copied_files
  notify:
    - test configuration
