---
- name: Install logroate configuration
  when: logrotate_uninstall == false
  block:
    - name: Install
      ansible.builtin.include_tasks: install.yml

    - name: Setup
      ansible.builtin.include_tasks: setup.yml

- name: Uninstall logroate configuration
  when: logrotate_uninstall == true
  block:
    - name: Clean
      ansible.builtin.include_tasks: clean.yml
